case_path:  /cfdfile1/data/fm/radiputr/Documents/02_Simulation/SBM/examples/channel_bubble
purge_boundary_data: True     # Purges old boundary data directory
profile_run:         False    # Profile code execution
packages:
  cfd_program:  OpenFOAM
  cfd_version:  v2312-foss-2023a
  python_version: Anaconda3-python/2023.09-0