case_path:  /path/to/your/openfoam/case
purge_boundary_data: True     # Purges old boundary data directory
packages:
  cfd_program:  OpenFOAM
  cfd_version:  v2312-foss-2023a
  python_version: Anaconda3-python/2023.09-0
simulation_parameters:
  dimension:  3               # Number of dimension
  start_time: 0               # Start time of simulation
  end_time: 0.5               # End time of simulation
  delta_time: 0.002           # Time step size
  inlet_name: inlet           # Name of inlet boundary patch
  fluid_name: Water           # Name of fluid. Corresponds to alpha.<fluid_name> defined in OpenFOAM case
  rho_g:  1.225               # Density of gas
  rho_l:  998.2               # Density of liquid
sbm_parameters:
  t_unit: 0.1                 # Interval for bubble insertion
  mass_gas: 5e-6              # Mass of gas to be introduced
  mass_bubble_min:  5e-7      # min mass of single bubble to be inserted. Recommendation: 10% of mass_gas
  mass_bubble_max:  1e-6      # max mass of single bubble to be inserted. Recommendation: 20% of mass-gas
  mass_gas_tol:  1e-7         # Tolerance on the gas mass to be introduced in domain over a time 'tunit'
  velocity:         1         # Velocity of the mixture  to be introduced in domain
  intersect_boundary: True    # Allows bubbles to instersect domain boundary
  intersect_bubble: True      # Allows bubbles to intersect each other
fluent:
  max_nodes_per_face: 4
  time_step_start: 0
  n_time_steps: 50000
  case_name:  second_test.cas.h5
  cores:  4 