#!/bin/bash

runParallel()
{
    nproc="$1"
    shift
    exe="$(which $1)"
    sol=$(basename -- "$1")
    sol="${sol%.*}"
    shift
    if [ -f log."$sol" ]; then rm log."$sol"; fi
    export OMPI_MCA_btl_vader_single_copy_mechanism=none  # Workaround for open-mpi/docker bug
    mpiexec  -np $nproc "$exe" -parallel "$@" 1> >(tee -a log."$sol") 2> >(tee -a log."$sol" >&2)
    err=$?
    if [ ! $err -eq 0 ]; then exit $err; fi
}

runCommand()
{
    sol=$(basename -- "$1")
    sol="${sol%.*}"
    if [ -f log."$sol" ]; then rm log."$sol"; fi
    "$@" 1> >(tee -a log."$sol") 2> >(tee -a log."$sol" >&2)
    err=$?
    if [ ! $err -eq 0 ]; then exit $err; fi
}

# Unset and source bashrc
FOAMDIR="/apps/RHEL8/EasyBuild/software/OpenFOAM/v2312-foss-2023a/OpenFOAM-v2312"
if [ ! -z "$FOAMDIR" ]
then
    source "$FOAMDIR/etc/config.sh/unset" 2> /dev/null
    source "$FOAMDIR/etc/bashrc"
fi

# Detect available turbulence lib
if [ -f "$FOAM_LIBBIN/libmomentumTransportModels.so" ] || [ -f "$FOAM_LIBBIN/libmomentumTransportModels.dll" ]
then
    echo \"libmomentumTransportModels.so\" > system/turbulenceLib
else
    echo \"libturbulenceModels.so\" > system/turbulenceLib
fi

# Change specification of interface compression in OF 13+
if [ -z ${FOAM_API+x} ] && [ "$WM_PROJECT_VERSION" -ge 13 ]
then
    echo "div(phi,alpha) Gauss interfaceCompression vanLeer 1;" > system/alphaDivScheme
    echo "" > system/cAlpha
else
    echo "div(phi,alpha) Gauss vanLeer;" > system/alphaDivScheme
    echo "cAlpha 1;" > system/cAlpha
fi


PNAME=p_rgh

# Parallel decomposition
if [ ! -d processor0 ]
then
    runCommand decomposePar -force
fi

# Pick up number of parallel processes
NPROC=$(foamDictionary -entry "numberOfSubdomains" -value system/decomposeParDict)

# Mesh renumbering
#runParallel $NPROC renumberMesh -overwrite

# Initialise flow
runParallel $NPROC potentialFoam -initialiseUBCs -pName $PNAME
# Remove phi with wrong units
rm -f processor*/0/phi

# Run application in parallel
# Detect new foamRun in Foundation versions >= 11 and translate solver
which foamRun > /dev/null 2>&1
if [ $? == 0 ]
then
    runParallel $NPROC foamRun -solver incompressibleVoF
else
    runParallel $NPROC interFoam
fi

