#!/bin/bash

runCommand()
{
    sol=$(basename -- "$1")
    sol="${sol%.*}"
    if [ -f log."$sol" ]; then rm log."$sol"; fi
    "$@" 1> >(tee -a log."$sol") 2> >(tee -a log."$sol" >&2)
    err=$?
    if [ ! $err -eq 0 ]; then exit $err; fi
}

# Detect available turbulence lib
if [ -f "$FOAM_LIBBIN/libmomentumTransportModels.so" ] || [ -f "$FOAM_LIBBIN/libmomentumTransportModels.dll" ]
then
    echo \"libmomentumTransportModels.so\" > system/turbulenceLib
else
    echo \"libturbulenceModels.so\" > system/turbulenceLib
fi

# Change specification of interface compression in OF 13+
if [ -z ${FOAM_API+x} ] && [ "$WM_PROJECT_VERSION" -ge 13 ]
then
    echo "div(phi,alpha) Gauss interfaceCompression vanLeer 1;" > system/alphaDivScheme
    echo "" > system/cAlpha
else
    echo "div(phi,alpha) Gauss vanLeer;" > system/alphaDivScheme
    echo "cAlpha 1;" > system/cAlpha
fi

# Copy mesh from meshCase
MESHDIR="../meshCase"
if [ -f "$MESHDIR"/constant/polyMesh/faces ]
then
    rm -rf constant/polyMesh
    cp -r "$MESHDIR"/constant/polyMesh constant/polyMesh
elif [ ! -f constant/polyMesh/faces ]
then
    echo "Fatal error: Unable to find mesh in directory $MESHDIR" 1>&2
    exit 1
fi

# rename patch names
runCommand createPatch -overwrite

